package faroo

const(
	//The API_KEY that has been defined in Google-Console.
	//Live
	//API_KEY = ""
	//Dev
	API_KEY = ""
	
	PUSH_SENDER = "https://android.googleapis.com/gcm/send"
  	PUSH_KEY = "key=" + API_KEY
  	API_METHOD = "POST"
  	API_RESTYPE = "application/json"
	TOPICS = "/topics/"
	
	//The FAROO_KEY that is generated by fraoo.com, see more: http://www.faroo.com/hp/api/api.html#key
	//Live
	//FAROO_KEY = ""
	//Dev
	FAROO_KEY = ""
	FAROO_API = "http://www.faroo.com/api?q=%s&start=1&length=1&l=%s&src=news&f=json&key=" + FAROO_KEY
)  